=== octgn/OCTGN/octgnFX/Octgn.Server/protocol.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="protocol">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="msg" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="param" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="name" use="required" type="xs:string" />
                  <xs:attribute name="type" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="byte" />
                        <xs:enumeration value="ushort" />
                        <xs:enumeration value="short" />
                        <xs:enumeration value="short[]" />
                        <xs:enumeration value="int" />
                        <xs:enumeration value="int[]" />
                        <xs:enumeration value="ulong" />
                        <xs:enumeration value="ulong[]" />
                        <xs:enumeration value="float" />
                        <xs:enumeration value="bool" />
                        <xs:enumeration value="string" />
                        <xs:enumeration value="string[]" />
                        <xs:enumeration value="Version" />
                        <xs:enumeration value="Guid" />
                        <xs:enumeration value="Guid[]" />
                        <xs:enumeration value="Player" />
                        <xs:enumeration value="Player[]" />
                        <xs:enumeration value="ControllableObject" />
                        <xs:enumeration value="Group" />
                        <xs:enumeration value="Group[]" />
                        <xs:enumeration value="Card" />
                        <xs:enumeration value="Counter" />
                        <xs:enumeration value="CardOrientation" />
                        <xs:enumeration value="Color" />
                        <xs:enumeration value="Color?" />
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:string" />
            <xs:attribute name="server" default="false" type="xs:boolean" />
            <xs:attribute name="client" default="false" type="xs:boolean" />
          </xs:complexType>
        </xs:element>
        <xs:element name="skipnum" maxOccurs="unbounded" minOccurs="0">
          
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== octgn/OCTGN/octgnFX/Octgn.Server/Protocol.xml
<protocol xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="protocol.xsd">
  <msg name="Error" server="true" client="true" anonymous="true">
    <param name="msg" type="string" />
  </msg>

  <msg name="Boot" server="true">
    <param name="player" type="Player"/>
    <param name="reason" type="string"/>
  </msg>

  <msg name="Kick" client="true">
    <param name="reason" type="string"/>
  </msg>

  <msg name="Hello" server="true" allowedbyspectator="true" anonymous="true">
    <param name="nick" type="string" />
    <param name="userId" type="string" />
    <param name="pkey" type="ulong" />
    <param name="client" type="string" />
    <param name="clientVer" type="Version" />
    <param name="octgnVer" type="Version" />
    <param name="gameId" type="Guid" />
    <param name="gameVersion" type="Version" />
    <param name="password" type="string"/>
    <param name="spectator" type="bool"/>
  </msg>
  <msg name="HelloAgain" server="true" anonymous="true">
    <param name="pid" type="byte"/>
    <param name="nick" type="string" />
    <param name="userId" type="string" />
    <param name="pkey" type="ulong" />
    <param name="client" type="string" />
    <param name="clientVer" type="Version" />
    <param name="octgnVer" type="Version" />
    <param name="gameId" type="Guid" />
    <param name="gameVersion" type="Version" />
    <param name="password" type="string"/>
  </msg>
  <msg name="Welcome" client="true">
    <param name="id" type="byte" />
    <param name="gameSessionId" type="Guid"/>
    <param name="gameName" type="string"/>
    <param name="waitForGameState" type="bool"/>
  </msg>
  <msg name="Settings" server="true" client="true" allowedbyspectator="true">
    <param name="twoSidedTable" type="bool" />
    <param name="allowSpectators" type="bool"/>
    <param name="muteSpectators" type="bool"/>
    <param name="allowCardList" type="bool"/>
  </msg>
  <msg name="PlayerSettings" server="true" client="true" allowedbyspectator="true">
    <param name="playerId" type="PlayerOrSpectator" />
    <param name="invertedTable" type="bool" />
    <param name="spectator" type="bool"/>
  </msg>
  <msg name="NewPlayer" client="true">
    <param name="id" type="byte" />
    <param name="nick" type="string" />
    <param name="userId" type="string" />
    <param name="pkey" type="ulong" />
    <param name="tableSide" type="bool"/>
    <param name="spectator" type="bool"/>
  </msg>
  <msg name="Leave" client="true" server="true" allowedbyspectator="true">
    <param name="player" type="PlayerOrSpectator" />
  </msg>
  <msg name="Start" client="true" server="true" />
  <msg name="ResetReq" server="true" >
    <param name="isSoft" type="bool" />
  </msg>
  <msg name="Reset" client="true">
    <param name="player" type="Player" />
    <param name="isSoft" type="bool" />
  </msg>

  <msg name="NextTurn" client="true" server="true">
    <param name="player" type="Player" />
    <param name="setActive" type="bool" />
    <param name="force" type="bool" />
  </msg>

  <msg name="StopTurnReq" server="true">
    <param name="turnNumber" type="int" />
    <param name="stop" type="bool" />
  </msg>
  <msg name="StopTurn" client="true">
    <param name="player" type="Player" />
  </msg>

  <msg name="SetPhaseReq" server="true">
    <param name="nextPhase" type="byte" />
    <param name="force" type="bool" />
  </msg>
  <msg name="SetPhase" client="true">
    <param name="phase" type="byte" />
    <param name="players" type="Player[]" />
    <param name="force" type="bool" />
  </msg>

  <msg name="StopPhaseReq" server="true">
    <param name="phase" type="byte" />
    <param name="stop" type="bool" />
  </msg>

  <msg name="SetActivePlayer" client="true" server="true">
    <param name="player" type="Player" />
  </msg>

  <msg name="ClearActivePlayer" client="true" server="true">
  </msg>

  <msg name="ChatReq" server="true" allowedbyspectator="true">
    <param name="text" type="string" />
  </msg>
  <msg name="Chat" client="true" allowedbyspectator="true">
    <param name="player" type="PlayerOrSpectator" />
    <param name="text" type="string" />
  </msg>
  <msg name="PrintReq" server="true" allowedbyspectator="true">
    <param name="text" type="string" />
  </msg>
  <msg name="Print" client="true" allowedbyspectator="true">
    <param name="player" type="PlayerOrSpectator" />
    <param name="text" type="string" />
  </msg>

  <msg name="RandomReq" server="true">
    <param name="min" type="int" />
    <param name="max" type="int" />
  </msg>
  <msg name="Random" client="true">
    <param name="result" type="int" />
  </msg>
  <msg name="CounterReq" server="true">
    <param name="counter" type="Counter" />
    <param name="value" type="int" />
    <param name="isScriptChange" type="bool"/>
  </msg>
  <msg name="Counter" client="true">
    <param name="player" type="Player" />
    <param name="counter" type="Counter" />
    <param name="value" type="int" />
    <param name="isScriptChange" type="bool"/>
  </msg>

  <msg name="LoadDeck" server="true" client="true">
    <param name="id" type="int[]" />
    <param name="type" type="Guid[]" />
    <param name="group" type="Group[]" />
    <param name="size" type="string[]" />
    <param name="sleeve" type="string"/>
    <param name="limited" type="bool"/>
  </msg>
  <msg name="CreateCard" server="true" client="true">
    <param name="id" type="int[]" />
    <param name="type" type="Guid[]" />
    <param name="size" type="string[]" />
    <param name="group" type="Group" />
  </msg>
  <msg name="CreateCardAt" server="true" client="true">
    <param name="id" type="int[]" />
    <param name="modelId" type="Guid[]" />
    <param name="x" type="int[]" />
    <param name="y" type="int[]" />
    <param name="faceUp" type="bool" />
    <param name="persist" type="bool" />
  </msg>
  <msg name="CreateAliasDeprecated" server="true" client="true">
    <param name="id" type="int[]" />
    <param name="type" type="ulong[]" />
  </msg>

  <msg name="MoveCardReq" server="true">
    <param name="id" type="int[]" />
    <param name="group" type="Group" />
    <param name="idx" type="int[]" />
    <param name="faceUp" type="bool[]" />
    <param name="isScriptMove" type="bool"/>
  </msg>
  <msg name="MoveCard" client="true">
    <param name="player" type="Player" />
    <param name="id" type="int[]" />
    <param name="group" type="Group" />
    <param name="idx" type="int[]" />
    <param name="faceUp" type="bool[]" />
    <param name="isScriptMove" type="bool"/>
  </msg>
  <msg name="MoveCardAtReq" server="true">
    <param name="id" type="int[]" />
    <param name="x" type="int[]" />
    <param name="y" type="int[]" />
    <param name="idx" type="int[]" />
    <param name="isScriptMove" type="bool"/>
    <param name="faceUp" type="bool[]" />
  </msg>
  <msg name="MoveCardAt" client="true">
    <param name="player" type="Player" />
    <param name="id" type="int[]" />
    <param name="x" type="int[]" />
    <param name="y" type="int[]" />
    <param name="idx" type="int[]" />
    <param name="faceUp" type="bool[]" />
    <param name="isScriptMove" type="bool"/>
  </msg>
  <msg name="PeekReq" server="true">
    <param name="card" type="Card" />
  </msg>
  <msg name="Peek" client="true">
    <param name="player" type="Player" />
    <param name="card" type="Card" />
  </msg>

  <msg name="UntargetReq" server="true">
    <param name="card" type="Card" />
    <param name="isScriptChange" type="bool" />
  </msg>
  <msg name="Untarget" client="true">
    <param name="player" type="Player" />
    <param name="card" type="Card" />
    <param name="isScriptChange" type="bool" />
  </msg>
  <msg name="TargetReq" server="true">
    <param name="card" type="Card" />
    <param name="isScriptChange" type="bool" />
  </msg>
  <msg name="Target" client="true">
    <param name="player" type="Player" />
    <param name="card" type="Card" />
    <param name="isScriptChange" type="bool" />
  </msg>
  <msg name="TargetArrowReq" server="true">
    <param name="card" type="Card" />
    <param name="otherCard" type="Card" />
    <param name="isScriptChange" type="bool" />
  </msg>
  <msg name="TargetArrow" client="true">
    <param name="player" type="Player" />
    <param name="card" type="Card" />
    <param name="otherCard" type="Card" />
    <param name="isScriptChange" type="bool" />
  </msg>

  <msg name="Highlight" server="true" client="true">
    <param name="card" type="Card" />
    <param name="color" type="Color?" />
  </msg>

  <msg name="TurnReq" server="true">
    <param name="card" type="Card" />
    <param name="up" type="bool" />
  </msg>
  <msg name="Turn" client="true">
    <param name="player" type="Player" />
    <param name="card" type="Card" />
    <param name="up" type="bool" />
  </msg>

  <msg name="RotateReq" server="true">
    <param name="card" type="Card" />
    <param name="rot" type="CardOrientation" />
  </msg>
  <msg name="Rotate" client="true">
    <param name="player" type="Player" />
    <param name="card" type="Card" />
    <param name="rot" type="CardOrientation" />
  </msg>

  <msg name="ShuffleDeprecated" client="true" server="true">
    <param name="group" type="Group" />
    <param name="card" type="int[]" />
  </msg>
  <msg name="Shuffled" client="true" server="true">
    <param name="player" type="Player" />
    <param name="group" type="Group" />
    <param name="card" type="int[]" />
    <param name="pos" type="short[]" />
  </msg>
  <msg name="UnaliasGrpDeprecated" client="true" server="true">
    <param name="group" type="Group" />
  </msg>
  <msg name="UnaliasDeprecated" client="true" server="true">
    <param name="card" type="int[]" />
    <param name="type" type="ulong[]" />
  </msg>
  <msg name="AddMarkerReq" server="true">
    <param name="card" type="Card" />
    <param name="id" type="string" />
    <param name="name" type="string" />
    <param name="count" type="ushort" />
    <param name="origCount" type="ushort"/>
